schema_version = "1.7.0"
modified = "2025-05-30T00:00:00Z"
published = "2025-05-30T00:00:00Z"
summary = "Firefox -- unencrypted SNI"
details = """
security@mozilla.org reports:

> In certain cases, SNI could have been sent unencrypted
> even when encrypted DNS was enabled."""
references = [
    { type = "ADVISORY", url = "https://api.osv.dev/v1/vulns/CVE-2025-5270" },
    { type = "ADVISORY", url = "https://nvd.nist.gov/vuln/detail/CVE-2025-5270" },
]
affected = []
id = "FBSD-2025-0109"

[database_specific]
vid = "a470ac63-3d7c-11f0-9a55-b42e991fc52e"
discovery = "2025-05-27T00:00:00Z"
